### ISSUE TITLE
Yazım hatası

### ISSUE THREAD

**Issue by noktafa** [aspnet/AspNetCore.Docs.tr-tr#12]
https://docs.microsoft.com/tr-tr/aspnet/core/?view=aspnetcore-3.1#why-use-aspnet-core
basligi altinda ISS,
IIS olarak düzeltilmeli.

[Geri bildiriminizi buraya girin]

---
#### Belge Ayrıntıları

⚠ *Bu bölümü düzenlemeyin. docs.microsoft.com ➟ GitHub sorunu bağlantısı için gereklidir.*

* ID: ad8c13e7-78e6-cf9a-e7cb-3215df5fd1c4
* Version Independent ID: a3c1d2a6-625a-3409-120d-8372230a8196
* Content: [ASP.NET Core’a Giriş](https://docs.microsoft.com/tr-tr/aspnet/core/?view=aspnetcore-3.1#feedback)
* Content Source: [aspnetcore/index.md](https://github.com/aspnet/AspNetCore.Docs.tr-tr/blob/live/aspnetcore/index.md)
* Product: **aspnet-core**
* Technology: **aspnetcore**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @noktafa
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Merhaba @noktafa,   

Geri bildiriminiz için teşekkür ederiz.  

Dil ekibimiz, dil önerilerinizi gözden geçirdi ve kabul etti. Geri bildiriminizi uyguladık ve Docs sitesindeki https://docs.microsoft.com/tr-tr/aspnet/core/?view=aspnetcore-3.1#feedback sayfalarında bulunan makaleleri güncelleştirdik.   

Makalelerimize yaptığınız katkı için çok teşekkür eder, değerli görüşlerinizi bizimle paylaşmaya devam etmenizden mutluluk duyarız.  

Saygılarımla,  
Microsoft DOCS Uluslararası Ekibi
